# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

GOOGLE_APP_ID: '870142329409-rq0ruiijoeeenhcqdkqpunblvtohe81c.apps.googleusercontent.com'  
GOOGLE_APP_SECRET: 'MVoUnyuKVfY-vqrOCDfNZcEh'

GOOGLE_MAPS_API_KEY: 'AIzaSyB7BkN0mhT_tppFOcF-STOg9AiKRcmaTDU'

FACEBOOK_KEY: '1173195899504459'
FACEBOOK_SECRET: 'f6c431ae2b6536de75c102df730924e7'

# development:
#   AWS_ACCESS_KEY_ID: 'AKIAJQV3SKWE5Q6VJSCA'
#   AWS_SECRET_ACCESS_KEY: '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'

# test:
#   AWS_ACCESS_KEY_ID: 'AKIAJQV3SKWE5Q6VJSCA'
#   AWS_SECRET_ACCESS_KEY: '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'
# production:
#   AWS_ACCESS_KEY_ID: 'AKIAJQV3SKWE5Q6VJSCA'
#   AWS_SECRET_ACCESS_KEY: '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'

AWS_ACCESS_KEY_ID: "AKIAJQV3SKWE5Q6VJSCA"
AWS_SECRET_ACCESS_KEY: "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"
S3_BUCKET_NAME: "crypto-portfolio-simulator"
AWS_REGION: "us-east-1"

# BRAINTREE_MERCHANT_ID: 't2sy9nwv79mmyszb'
# BRAINTREE_PUBLIC_KEY: 'drnzq7hj6rwvsmt9'
# BRAINTREE_PRIVATE_KEY: 'a984182f686da8bef6e89bbd4e474046'

# GMAIL_USERNAME: 'fjclonebnb@gmail.com'
# GMAIL_PASSWORD: 'clonebnb2018'

# REDIS_URL: 'redis://localhost:6379/0/cache'