development:
  host: 'localhost'
  port: '6379'
test:
  host: 'localhost'
  port: '6379'
production:
  host: 'ec2-34-192-25-148.compute-1.amazonaws.com'
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: stock-portfolio-simulator_production
  port: '587'